### ISSUE TITLE
Updated 3.1 TCK release (3.1.1)

### ISSUE THREAD

**Issue by mswatosh** [jakartaee/validation-tck#199]
The latest 3.1 TCK release on the staging repo is from March, @starksm64 can we get an updated release with the new fixes?

**Comment by marko-bekhta** [comment]
+1 for the release 😃

**Comment by starksm64** [comment]
The 3.1.1 is staged:
https://www.eclipse.org/downloads/download.php?file=/ee4j/bean-validation/3.1/validation-tck-dist-3.1.1.zip

I'll create a new spec repo PR to update the latest Validation TCK version and it will need to be promoted by a spec committee member.

**Comment by jungm** [comment]
Is there a reason why the maven artifacts haven't been promoted to the release repository yet?

Not that familiar with how releases are handled in Jakarta EE/Eclipse Foundation, but the TCK is already linked [here](https://jakarta.ee/specifications/bean-validation/3.1/) with no mention of it being staged. So I guess it's released?

I recently integrated the 3.1.1 TCK in Apache BVal and would really like to drop the jakarta staging repository again from the pom

**Comment by mswatosh** [comment]
@starksm64 Can you run the maven release jenkins build to promote this to maven central as well?

**Comment by jungm** [comment]
Any updates?

**Comment by starksm64** [comment]
The release has been promoted to maven central
